version: '3.8'

services:

  njs-stress-test:
    build:
      context: .
      dockerfile: ./njs/Dockerfile
    environment:
      USER_FETCH_URL: 'http://nginx:80/'
      SECRETS: '{"mysupersecretkey":"123123123"}'
    volumes:
      - .:/app
    ports:
      - "8028:8008"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

  nodejs-stress-test:
    build:
      context: .
      dockerfile: ./nodejs/Dockerfile
    environment:
      USER_FETCH_URL: 'http://nginx:80/'
      SECRETS: '{"mysupersecretkey":"123123123"}'
    volumes:
      - .:/app
    ports:
      - "3023:3003"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

  fake-oauth:
    image: acando14/fake-oauth2
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    ports:
      - "8099:80"