version: '3.8'

services:

  njs-stress-test-open:
    build:
      context: .
      dockerfile: ./njs/Dockerfile
    environment:
      USER_FETCH_URL: 'http://logger:8099'
      SECRETS: '{"mysupersecretkey":"123123123"}'
    volumes:
      - .:/app
    ports:
      - "8028:8008"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1GB

  nodejs-stress-test-open:
    build:
      context: .
      dockerfile: ./nodejs/Dockerfile
    environment:
      USER_FETCH_URL: 'http://localhost:8099'
      SECRETS: '{"mysupersecretkey":"123123123"}'
    volumes:
      - .:/app
    ports:
      - "3023:3003"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1GB

  njs-stress-test-slim:
    build:
      context: .
      dockerfile: ./njs/Dockerfile
    environment:
      USER_FETCH_URL: 'http://localhost:8099'
      SECRETS: '{"mysupersecretkey":"123123123"}'
    volumes:
      - .:/app
    ports:
      - "8018:8008"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M

  nodejs-stress-test-slim:
    build:
      context: .
      dockerfile: ./nodejs/Dockerfile
    environment:
      USER_FETCH_URL: 'http://localhost:8099'
      SECRETS: '{"mysupersecretkey":"123123123"}'
    volumes:
      - .:/app
    ports:
      - "3013:3003"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M

  fake-oauth:
    image: acando14/fake-oauth2
    ports:
      - "8080:8080"

  logger:
    image: acando14/logger-server:latest
    ports:
      - "8099:8099"