version: '3.8'

services:
  njs-functional-test:
    build:
      context: .
      dockerfile: ./njs/Dockerfile
    environment:
      USER_FETCH_URL: 'http://fake-oauth:8080/idp/userinfo.openid'
      SECRETS: '{"mysupersecretkey":"123123123"}'
    entrypoint: [ "/usr/sbin/nginx", "-g", "daemon off;error_log /dev/stdout debug;" ]
    volumes:
      - .:/app
    ports:
      - "8008:8008"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 50M

  nodejs-functional-test:
    build:
      context: .
      dockerfile: ./nodejs/Dockerfile
    environment:
      USER_FETCH_URL: 'http://fake-oauth:8080/idp/userinfo.openid'
      SECRETS: '{"mysupersecretkey":"123123123"}'
    volumes:
      - .:/app
    ports:
      - "3003:3003"

  fake-oauth:
    image: acando14/fake-oauth2
    ports:
      - "8080:8080"